### ISSUE TITLE
create a Dockerfile

### ISSUE THREAD

**Issue by metaver5o** [8go/TrezorSymmetricFileEncryption#8]
Hi,
it would be useful to have a Dockerfile to get this running quik and easy.
as well some requirements.txt file for python, I have been trying all day to make this work without success. If I get this to work, I will create a PR to add the Dockerfile and how to use it.
thanks,
Marco

**Comment by metaver5o** [comment]
just as a matter of context, this is what I am stuck:

```
# python3 TrezorSymmetricFileEncryption.py
Traceback (most recent call last):
  File "TrezorSymmetricFileEncryption.py", line 23, in <module>
    from dialogs import Dialog
  File "/TrezorSymmetricFileEncryption/dialogs.py", line 20, in <module>
    from processing import processAll
  File "/TrezorSymmetricFileEncryption/processing.py", line 19, in <module>
    from trezorlib.client import CallException, PinException
ImportError: cannot import name 'CallException'
```
and

```
# ./TrezorSymmetricFileEncryption.py 
Traceback (most recent call last):
  File "./TrezorSymmetricFileEncryption.py", line 21, in <module>
    from PyQt5.QtWidgets import QApplication  # for the clipboard and window
ImportError: No module named PyQt5.QtWidgets

```

**Comment by metaver5o** [comment]
trying to run in docker container, mounted as `--privileged -v /dev/bus/usb:/dev/bus/usb` 
ubuntu bionic, python3

**Comment by metaver5o** [comment]
Hi, nevermind as I was able to encrypt/decrypt my files signing with trezor-agent and gpg.
thanks

**Comment by qkum** [comment]
> Hi, nevermind as I was able to encrypt/decrypt my files signing with trezor-agent and gpg. thanks

So, the error you linked did not matter in the end or what?

- Thanks for adding the Docker file btw.
